image: haskell:8.10.7

stages:
  - functions
  - lists
  - optional

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"
  STACK_OPTS: "--system-ghc"

operators:
  stage: functions
  script:
    - stack $STACK_OPTS test :operators

functions:
  stage: functions
  script:
    - stack $STACK_OPTS test :functions

collatz:
  stage: functions
  script:
    - stack $STACK_OPTS test :collatz

fact:
  stage: functions
  script:
    - stack $STACK_OPTS test :fact

binom:
  stage: functions
  script:
    - stack $STACK_OPTS test :binom

ggT:
  stage: functions
  script:
    - stack $STACK_OPTS test :ggt

fib:
  stage: functions
  script:
    - stack $STACK_OPTS test :fib

deMorgan:
  stage: functions
  script:
    - stack $STACK_OPTS test :demorgan

comprehension:
  stage: lists
  script:
    - stack $STACK_OPTS test :comprehension

mapfilter:
  stage: lists
  script:
    - stack $STACK_OPTS test :mapfilter

recursion:
  stage: lists
  script:
    - stack $STACK_OPTS test :recursion

foldr:
  stage: lists
  script:
    - stack $STACK_OPTS test :foldr

foldl:
  stage: lists
  script:
    - stack $STACK_OPTS test :foldl

concatmap:
  stage: lists
  script:
    - stack $STACK_OPTS test :concatmap

morefun:
  stage: optional
  script:
    - stack $STACK_OPTS test :morefun

listmonad:
  stage: optional
  script:
    - stack $STACK_OPTS test :listmonad

adtlist:
  stage: optional
  script:
    - stack $STACK_OPTS test :adtlist

andoranyall:
  stage: optional
  script:
    - stack $STACK_OPTS test :andoranyall

minimummaximum:
  stage: optional
  script:
    - stack $STACK_OPTS test :minimummaximum

